### PR TITLE
Updated stackoverflow icon color

### PR DESCRIPTION
**Pull request by arpitjindal97**

### CODE REVIEW

**Comment by mudassir0909** [comment]
@arpitjindal97 heya, thanks for the contribution, can you also post a screenshot of how the change looks?

**Comment by arpitjindal97** [comment]
whatsapp image 2017-08-01 at 11 44 54 am

It looks like the official one

**Comment by arpitjindal97** [comment]
Either merge the PR or close it. You are taking too long to take any action

**Comment by mudassir0909** [comment]
>  Either merge the PR or close it. You are taking too long to take any action

I have a full-time job, which means I get to review my open-source projects over the weekend & some times I go out on the weekends! It'd be good if you follow BNBR, as this is not a super-high-priority bug fix!

Cheers

**Pull request merged**
