### PR TITLE
Normalize Gravatar image size

### LINKED ISSUE #30: Images being enlarged and pixelating
The Gravatar images that are being brought in from Gravatar appear to be 80px, maybe 64px at one point in the past, but also want to be 100px. The result is that a smaller picture is being used and and appears pixelated against an otherwise really crisp page.

### PR DESCRIPTION
**Pull request by chrisvogt**
My Gravatar image was coming out unpleasantly blurry juxtaposed with the rest of this fine, sharp layout. Removed the CSS enlarging the image by 20px, and normalized the loaded image and the image's defined style to 100px. This should fix #30.

### CODE REVIEW

**Comment by mudassir0909** [comment]
This PR moves the inline image styles to LESS file, uses "name" for the `alt` attribute, makes sure 64px64px image is not used for the holder.

But, I don't see any changes related to the statement **Removed the CSS enlarging the image by 20px** and **normalized the loaded image**. Did you miss something ?

**Comment by chrisvogt** [comment]
You are not missing anything. I worded that poorly. Here is a better explanation and a screenshot:

* The Gravatar helper _appears_ to be setup to get a 64px square image.
* Instead it appears to load an 80px image and then enlarges it to 100px using CSS.
* **Now** it loads a 100px image, and that image is not resized.

elegant-resume-screenshot

**Comment by chrisvogt** [comment]
After looking up what `holder.js` is,  does that actually need to be changed to ```data-src="holder.js/100x100" ```?

**Comment by mudassir0909** [comment]
The gravatar [helper](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/index.js#L96) already loads 100px image. I was loading 64px image holder but not the gravatar image.

Btw, `src="holder.js/100x100"` is a better option.

**Pull request merged**
