### PR TITLE
Validate EndDate for project and work section

### PR DESCRIPTION
**Pull request by vikytech**
JSON validator cribs if the end date is missing in the json.

So added a check if the given date is future date then we mark it as "present".

This also fixes the duration for the same.

### CODE REVIEW

**Comment by vikytech** [comment]
@mudassir0909 Can you please help review?

**Comment by mudassir0909** [comment]
> given date is future date then we mark it as "present".

Why would we want to do this?

**Comment by vikytech** [comment]
> Why would we want to do this? it is normal to be working on a project with an end date in future, right?

If the end date is blank, the json-resume validator throws error.
To over come this
   * If we give a future date instead just to make the validator happy
*  Then the resume generated will have incorrect data for the last project/ work experience 😞 .


With this MR the details are generated properly and also the json-resume validator is happy.

 Win-Win situation 😎 

What's your thought on that ? @mudassir0909  🤔

**Comment by mudassir0909** [comment]
> If the end date is blank, the json-resume validator throws error.

If the end date is blank you won't even be able to publish the resume, the theme renderer only gets access to the valid json object i.e. in this case a non-null end date.

**Comment by vikytech** [comment]
> If the end date is blank you won't even be able to publish the resume, the theme renderer only gets access to the valid resume json object i.e. in this case a non-null end date.

I agree that is the point I am trying to overcome in the PR.

As we have [these](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/e5a81c596a975b6531a29aeba8513f06995c9cc5/pug/background/work-experience.pug#L15-L20) lines of code

https://github.com/mudassir0909/jsonresume-theme-elegant/blob/e5a81c596a975b6531a29aeba8513f06995c9cc5/pug/background/work-experience.pug#L15-L20

Well in that case this piece of code will never be executed right ?

I just liked that feature 😅

**Comment by vikytech** [comment]
Missing Duration example:

image

**Comment by mudassir0909** [comment]
I see the issue now, if what you want to add is duration for work experience that have `null` end dates then we could do it in a simpler fashion, 

Replace the following

https://github.com/mudassir0909/jsonresume-theme-elegant/blob/e5a81c596a975b6531a29aeba8513f06995c9cc5/index.js#L67-L69

with 

```js
     work_info.duration = work_info.endDate != null && end_date.isValid()
       ? moment.preciseDiff(start_date, end_date)
       : moment.preciseDiff(start_date, moment()); // if end date is not specified calculate duration as of today 
```

Thoughts?

**Comment by vikytech** [comment]
Sure, makes sense. 
Let me know if this looks good now ?

**Comment by vikytech** [comment]
I will delete and recreate this PR as there is lot of back and forth

**Pull request closed without merging**
